"""Change appointments to use start and end time

Revision ID: 373503cdb761
Revises: 3da2b222f582
Create Date: 2025-06-12 14:09:37.812798

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '373503cdb761'
down_revision: Union[str, None] = '3da2b222f582'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('start_time', sa.DateTime(), nullable=False))
    op.add_column('appointments', sa.Column('end_time', sa.DateTime(), nullable=False))
    op.drop_column('appointments', 'appointment_time')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('appointment_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_column('appointments', 'end_time')
    op.drop_column('appointments', 'start_time')
    # ### end Alembic commands ###
