"""Split full_name into first_name and last_name

Revision ID: 6ae82f7057b8
Revises: a8387de8ad47
Create Date: 2025-06-12 13:43:04.226880

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ae82f7057b8'
down_revision: Union[str, None] = 'a8387de8ad47'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('doctors', sa.Column('first_name', sa.String(), nullable=False))
    op.add_column('doctors', sa.Column('last_name', sa.String(), nullable=False))
    op.drop_column('doctors', 'full_name')
    op.add_column('patients', sa.Column('first_name', sa.String(), nullable=False))
    op.add_column('patients', sa.Column('last_name', sa.String(), nullable=False))
    op.drop_column('patients', 'full_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patients', sa.Column('full_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('patients', 'last_name')
    op.drop_column('patients', 'first_name')
    op.add_column('doctors', sa.Column('full_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('doctors', 'last_name')
    op.drop_column('doctors', 'first_name')
    # ### end Alembic commands ###
