"""Create admin record

Revision ID: c86bb0400409
Revises: e77f0b3a68ba
Create Date: 2025-06-13 21:28:12.405987

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from passlib.hash import bcrypt
from sqlalchemy.sql import text


# revision identifiers, used by Alembic.
revision: str = 'c86bb0400409'
down_revision: Union[str, None] = 'e77f0b3a68ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    hashed_password = bcrypt.hash("admin123")
    op.execute(f"""
        INSERT INTO users (email, hashed_password, role)
        VALUES ('admin@test.com', '{hashed_password}', 'admin')
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DELETE FROM users WHERE email = 'admin@test.com'")
    # ### end Alembic commands ###
