"""Link Doctor and Patient to User

Revision ID: e77f0b3a68ba
Revises: 3bf392d0de00
Create Date: 2025-06-13 18:59:39.577472

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e77f0b3a68ba'
down_revision: Union[str, None] = '3bf392d0de00'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DELETE FROM doctor_availabilities")
    op.execute("DELETE FROM appointments")
    op.execute("DELETE FROM doctors")
    op.execute("DELETE FROM patients")
    op.execute("DELETE FROM users")
    op.add_column('doctors', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_unique_constraint(None, 'doctors', ['user_id'])
    op.create_foreign_key(None, 'doctors', 'users', ['user_id'], ['id'])
    op.add_column('patients', sa.Column('user_id', sa.Integer(), nullable=False))
    op.drop_index(op.f('ix_patients_email'), table_name='patients')
    op.create_unique_constraint(None, 'patients', ['user_id'])
    op.create_foreign_key(None, 'patients', 'users', ['user_id'], ['id'])
    op.drop_column('patients', 'email')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patients', sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'patients', type_='foreignkey')
    op.drop_constraint(None, 'patients', type_='unique')
    op.create_index(op.f('ix_patients_email'), 'patients', ['email'], unique=True)
    op.drop_column('patients', 'user_id')
    op.drop_constraint(None, 'doctors', type_='foreignkey')
    op.drop_constraint(None, 'doctors', type_='unique')
    op.drop_column('doctors', 'user_id')
    # ### end Alembic commands ###
